; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Sat Oct 03 2020 15:00:14 GMT-0500 (CDT)
M83            ; relative extruder moves
G1 E-10 F3600  ; retract 10mm of filament
G91            ; relative positioning
G1 Z10 F360     ; lift Z by 10mm
G90            ; absolute positioning
G1 X-10 Y210 F6000 ; go to X=0 Y=0

