; tpre0.g
; called before tool 0 is selected
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Sat Oct 03 2020 15:00:14 GMT-0500 (CDT)
G90                                                    ; send absolute coordinates...
G21													   ; work in mm
M83                                                    ; ...but relative extruder moves
M200 D0
